import type { Metadata } from "next";
import localFont from "next/font/local";

import "./styles/global.scss";

const poppins = localFont({
  src: [
    {
      path: "./fonts/Poppins-Black.ttf",
      weight: "900",
    },
    {
      path: "./fonts/Poppins-Bold.ttf",
      weight: "700",
    },
    {
      path: "./fonts/Poppins-ExtraBold.ttf",
      weight: "800",
    },
    {
      path: "./fonts/Poppins-ExtraLight.ttf",
      weight: "200",
    },
    {
      path: "./fonts/Poppins-Light.ttf",
      weight: "300",
    },
    {
      path: "./fonts/Poppins-Regular.ttf",
      weight: "400",
    },
    {
      path: "./fonts/Poppins-Medium.ttf",
      weight: "500",
    },
    {
      path: "./fonts/Poppins-SemiBold.ttf",
      weight: "600",
    },
    {
      path: "./fonts/Poppins-Thin.ttf",
      weight: "100",
    },
  ],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Euphoria Shop App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable}`}>
      <body className="layout_container">{children}</body>
    </html>
  );
}
